# Generated by Django 5.1.1 on 2024-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ManyToManyField(related_name='created_by', to='user.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='course.content'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='course_enrolled_in', to='user.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='course_teacher', to='user.profile'),
        ),
    ]
