# Generated by Django 5.1.1 on 2024-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_content_created_by_course_content_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_by',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(blank=True, to='course.content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='course_enrolled_in', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='course_teacher', to='user.profile'),
        ),
    ]
