# Generated by Django 5.1.1 on 2024-10-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_content_created_by_alter_content_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
