# Generated by Django 5.1.1 on 2024-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_content_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
