# Generated by Django 5.1.1 on 2024-10-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_assignment_students_submissons'),
        ('course', '0005_content_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='assignment.assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='assignment.assignment'),
        ),
    ]
