# Generated by Django 5.1.1 on 2024-10-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_content_assignments_course_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
