# Generated by Django 5.1.1 on 2024-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_teacher_course_teachers'),
        ('user', '0003_discussion_liker_remove_discussion_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='discussions',
            field=models.ManyToManyField(blank=True, related_name='content_discussions', to='user.discussion'),
        ),
        migrations.AddField(
            model_name='course',
            name='discussions',
            field=models.ManyToManyField(blank=True, related_name='course_discussions', to='user.discussion'),
        ),
    ]
