# Generated by Django 5.1.1 on 2024-10-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('likes', models.ManyToManyField(blank=True, to='user.profile')),
                ('replies', models.ManyToManyField(blank=True, related_name='discussion_replies', to='user.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to='user.profile')),
            ],
        ),
    ]
