# Generated by Django 5.1.1 on 2024-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='liker',
            field=models.ManyToManyField(blank=True, to='user.profile'),
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
