# Generated by Django 5.1.1 on 2024-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_assigned_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(default='MCQ', max_length=20)),
                ('choices', models.ManyToManyField(blank=True, to='assignment.mcqchoice')),
            ],
        ),
    ]
