# Generated by Django 5.1.1 on 2024-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_mcqchoice_mcqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1000)),
                ('question_type', models.CharField(default='STRUCT', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='mcq_questions',
            field=models.ManyToManyField(blank=True, to='assignment.mcqquestion'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='struct_questions',
            field=models.ManyToManyField(blank=True, to='assignment.structuralquestion'),
        ),
    ]
