# Generated by Django 5.1.1 on 2024-10-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_structuralquestion_assignment_mcq_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
