# Generated by Django 5.1.1 on 2024-10-07 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_assignassignmentsubmission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignassignmentsubmission',
            name='score',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
