# Generated by Django 5.1.1 on 2024-10-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_assignassignmentsubmission_score'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignassignmentsubmission',
            old_name='score',
            new_name='total_score',
        ),
        migrations.CreateModel(
            name='MCQStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.mcqchoice')),
                ('question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.mcqquestion')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='assignassignmentsubmission',
            name='mcq_answers',
            field=models.ManyToManyField(blank=True, to='assignment.mcqstudentanswer'),
        ),
        migrations.CreateModel(
            name='StructuralStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2000)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True)),
                ('question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='struct_question', to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='assignassignmentsubmission',
            name='stuctural_answers',
            field=models.ManyToManyField(blank=True, to='assignment.structuralstudentanswer'),
        ),
    ]
