# Generated by Django 5.1.1 on 2024-10-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_rename_score_assignassignmentsubmission_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralstudentanswer',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.structuralquestion'),
        ),
    ]
