# Generated by Django 5.1.1 on 2024-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_alter_structuralstudentanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralstudentanswer',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
