# Generated by Django 5.1.1 on 2024-10-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_structuralstudentanswer_score'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignassignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='mcqstudentanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.mcqchoice'),
        ),
        migrations.AlterField(
            model_name='mcqstudentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.mcqquestion'),
        ),
        migrations.AlterField(
            model_name='mcqstudentanswer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='structuralstudentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.structuralquestion'),
        ),
        migrations.AlterField(
            model_name='structuralstudentanswer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='struct_question', to='user.profile'),
        ),
    ]
