# Generated by Django 5.1.1 on 2024-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_alter_assignassignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignassignmentsubmission',
            name='graded_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
