# Generated by Django 5.1.1 on 2024-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_alter_assignassignmentsubmission_graded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignassignmentsubmission',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
