# Generated by Django 5.1.1 on 2024-10-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_assignassignmentsubmission_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students_submissons',
            field=models.ManyToManyField(blank=True, related_name='all_submissions', to='assignment.assignassignmentsubmission'),
        ),
    ]
